apiVersion: v1
kind: Service
metadata:
  name: kube-struts-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: struts-8080-tcp
  type: NodePort
  selector:
    app: kube-struts-pod

---

apiVersion: v1
kind: Pod
metadata:
  name: kube-struts-pod
  labels:
    app: kube-struts-pod
spec:
  containers:
  - name: kube-struts-container
    image: dieterreuter/struts
